server {
    listen 80;
    # A lógica do sublinhado (_) é criar uma regra "catch-all".
    # O Nginx vai aceitar a requisição independentemente se você digitar localhost,
    # o IP 192.168.40.43 ou um domínio.
    server_name _;

    # Configurações comuns
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # API Spring Boot
    location /api/ {
        proxy_pass http://api:8080/;
    }

    location ~ ^/(swagger-ui|v3/api-docs|swagger-resources|webjars)/ {
        proxy_pass http://api:8080;
    }

    # Angular SSR
    location / {
        proxy_pass http://frontend:4000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}